### ISSUE TITLE
Get rid of animation time.

### ISSUE THREAD

**Issue by aZolo77** [react-bootstrap-table/react-bootstrap-table2#1336]
Can i somehow get rid of animating time when row expands?
It closes with freezes(

**Comment by AllenFang** [comment]
I guess you can try add these code in your code

```scss
.row-expand-slide-appear-active {
  transition: none !important;
}

.row-expand-slide-exit-active {
  transition: none !important;
}
```
