### ISSUE TITLE
How to remove label 'Filter by' ?

### ISSUE THREAD

**Issue by oleg41068** [react-bootstrap-table/react-bootstrap-table2#1794]
i'm run example https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-filter.html
How to remove label 'Filter by' ?

**Comment by basiliskarakitsios** [comment]
Did you find a solution?

**Comment by JaewukLee-E** [comment]
https://stackoverflow.com/questions/19758598/what-is-sr-only-in-bootstrap-3

Maybe It happend because there was no '.sr-only' css.
I added custom css file in react project
and wrote below
```css
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0,0,0,0);
  border: 0;
}
```

My case, It works
