### ISSUE TITLE
Cannot change pagination styling

### ISSUE THREAD

**Issue by bogannathan** [react-bootstrap-table/react-bootstrap-table2#270]
Is there any way to change the styling of the pagination list? I would like to have it centered under the table, but it by default adds columns that push it to the right. Is this a change I can do with this package?

Really appreciate it, looks good so far!

**Comment by Chun-MingChen** [comment]
Hi @bogannathan:

We're sorry for that so far `react-bootstrap-table2` is not able to allow users to customize `classNames` or `inline-style` for pagination bar. For this part any PR is welcomed. 

However, if it's bothering about the alignment, the following solution based on existing class does work but not recommended.

```css
.react-bootstrap-table-pagination-list {
  text-align: center;
  transform: translateX(-50%);
}

.react-bootstrap-table-page-btns-ul {
  float: none;
}
```
